apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-sykepenger-brukersporsmaalhandler
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
        - id: secure_logs
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
  azure:
    application:
      enabled: true
  image: {{image}}
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 60
    timeout: 90
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 60
    timeout: 90
  ingresses:
    - https://medlemskap-sykepenger-brukersporsmaalhandler.intern.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  strategy:
    type: Recreate
  secureLogs:
    enabled: true
  kafka:
    streams: true
    pool: nav-prod
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: login.microsoftonline.com
  env:
