apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: medlemskap-uavklart
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 2
    replication: 3
    retentionBytes: -1
    retentionHours: 2688
  acl:
    - team: medlemskap
      application: medlemskap-sykepenger-listener
      access: readwrite
